easy = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "French is an official language in Canada.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The color orange is named after the fruit.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Pluto is a planet.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Ping-Pong originated in England", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]

hard = [{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "Furby was released in 1998.", "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "You are allowed to sell your soul on eBay.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "Haggis is traditionally ate on Burns Night.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]
